export const discQuestions = [
    { id: 1, adjectives: ['Enthusiastic', 'Daring', 'Diplomatic', 'Satisfied'] },
    { id: 2, adjectives: ['Cautious', 'Determined', 'Convincing', 'Good-natured'] },
    { id: 3, adjectives: ['Friendly', 'Accurate', 'Outspoken', 'Calm'] },
    { id: 4, adjectives: ['Talkative', 'Controlled', 'Conventional', 'Decisive'] },
    { id: 5, adjectives: ['Adventurous', 'Insightful', 'Outgoing', 'Moderate'] },
    { id: 6, adjectives: ['Gentle', 'Persuasive', 'Humble', 'Original'] },
    { id: 7, adjectives: ['Expressive', 'Conscientious', 'Dominant', 'Responsive'] },
    { id: 8, adjectives: ['Poised', 'Observant', 'Modest', 'Impatient'] },
    { id: 9, adjectives: ['Tactful', 'Agreeable', 'Magnetic', 'Insistent'] },
    { id: 10, adjectives: ['Brave', 'Inspiring', 'Submissive', 'Timid'] },
    { id: 11, adjectives: ['Reserved', 'Obliging', 'Strong-willed', 'Cheerful'] },
    { id: 12, adjectives: ['Stimulating', 'Kind', 'Perceptive', 'Independent'] },
    { id: 13, adjectives: ['Competitive', 'Considerate', 'Joyful', 'Private'] },
    { id: 14, adjectives: ['Fussy', 'Obedient', 'Firm', 'Playful'] },
    { id: 15, adjectives: ['Attractive', 'Introspective', 'Stubborn', 'Predictable'] },
    { id: 16, adjectives: ['Logical', 'Bold', 'Loyal', 'Charming'] },
    { id: 17, adjectives: ['Sociable', 'Patient', 'Self-reliant', 'Self-spoken'] },
    { id: 18, adjectives: ['Willing', 'Eager', 'Thorough', 'High-spirited'] },
    { id: 19, adjectives: ['Aggressive', 'Extroverted', 'Amiable', 'Fearful'] },
    { id: 20, adjectives: ['Confident', 'Sympathetic', 'Impartial', 'Assertive'] },
    { id: 21, adjectives: ['Well-disciplined', 'Generous', 'Animated', 'Persistent'] },
    { id: 22, adjectives: ['Impulsive', 'Introverted', 'Forceful', 'Easygoing'] },
    { id: 23, adjectives: ['Good mixer', 'Refined', 'Vigorous', 'Lenient'] },
    { id: 24, adjectives: ['Captivating', 'Contented', 'Demanding', 'Compliant'] },
    { id: 25, adjectives: ['Argumentative', 'Systematic', 'Cooperative', 'Light-hearted'] },
    { id: 26, adjectives: ['Jovial', 'Precise', 'Direct', 'Even-tempered'] },
    { id: 27, adjectives: ['Restless', 'Neighborly', 'Appealing', 'Careful'] },
    { id: 28, adjectives: ['Respectful', 'Pioneering', 'Optimistic', 'Helpful'] }
];
    
    